### PR TITLE
Another core fix

### PR DESCRIPTION
**Pull request by MaxiBoether**

### CODE REVIEW

**Comment by bengelhaupt** [comment]
Indeed critical.

**Comment by felixrindt** [comment]
Did you check the code is still working? I'm not so sure about that.

**Comment by MaxiBoether** [comment]
No, why don't you provide this project with continuous integration? Would be your job as the core maintainer of this project.

**Comment by felixrindt** [comment]
CI doesn't include acceptance tests.

**Comment by MaxiBoether** [comment]
I didn't hear the SWT lecture yet, you know.

**Comment by felixrindt** [comment]
Just try running it.

**Comment by MaxiBoether** [comment]
you seriously expect me to install python? First, how about making a code of conduct for your project? cannot deal with this anymore.

**Pull request merged**
